language: java
jdk: openjdk8
addons:
  apt:
    packages:
      - libxtst-dev
services:
  - xvfb
before_install:
  - 'nvm install --lts'
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g vsce'
install:
  - 'npm ci'
  # https://github.com/travis-ci/travis-ci/issues/8813
  - 'rm -f ./node_modules/.bin/which'
  - 'vsce package'  
script:
  - 'npm test --silent'
  - 'npm run ui-test --silent'
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
    sonar-scanner;
    fi
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.npm"
env: DISPLAY=:99
branches:
  except:
    - /^dependabot.*$/
addons:
  sonarcloud:
    organization: "camel-tooling"
    branches:
      - master
